name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    if: github.ref == 'refs/heads/main' && github.repository == 'openai/openai-node'
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - uses: actions/checkout@v3

      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: 'openai'
          repositories: 'openai-node,openai-deno-build'

      - name: Set up Node
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          yarn install

      - name: Publish to NPM
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          bash ./bin/publish-npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
